/**
 * @brief - defines an event that gets generated by firewall.
 * 
 * @copyright - 2023-present All rights reserved. Devendra Naga.
*/
#ifndef __FW_EVENT_H__
#define __FW_EVENT_H__

#include <cstring>
#include <stdint.h>
#include <event_def.h>

namespace firewall {

/**
 * @brief - a detailed event information.
 * 
 * This is further used in storing an event temporarily.
*/
struct event {
    event_type evt_type;
    event_description evt_details;
    // matched rule id
    uint32_t rule_id;
    uint8_t src_mac[6];
    uint8_t dst_mac[6];
    uint16_t ethertype;
    uint32_t src_addr;
    uint32_t dst_addr;
    uint8_t ttl;
    uint32_t protocol;
    uint32_t src_port;
    uint32_t dst_port;
    uint32_t pkt_len;

    explicit event() : evt_type(event_type::Evt_Deny),
                       evt_details(event_description::Evt_Unknown_Error),
                       rule_id(0),
                       ethertype(0),
                       protocol(0),
                       src_port(0),
                       dst_port(0),
                       pkt_len(0)
    {
        std::memset(src_mac, 0, sizeof(src_mac));
        std::memset(dst_mac, 0, sizeof(dst_mac));
    }
    ~event() { }
};

}

#endif

